#!/usr/bin/env Rscript

suppressMessages(library(docopt))

## configuration for docopt
"Neolution - Schumacher lab neo-antigen prediction functionality. 

Usage: 
  neolution [options] <file>

Options:
  --mhc=<mhc>                    MHC/HLA allele, four-digit format [default: A0201].
  --length=<length>              Peptide length [default: 9].
  --affinity=<affinity>          netMHCpan affinity cutoff [default: NA].
  --processing=<processing>      Processing cutoff [default: 0.5].
  --ncores=<ncores>              Numbers of cores to use [default: 1].
  --rank=<rank>                  netMHCpan percentile rank cutoff [default: 1.9].
  --model=<model>                Random forest prediction model cutoff, optional suggested cutoff 0.02 for PBMC 0.01 for TIL screens [default: NA].
  --expression=<expression>      RNA expression cutoff [default: NA].
  --run_mode=<run_mode>          Type of predictions to be done [default: paired].
  --selfsim=<selfsim>            Perform simple self-similarity check; compatible with 9- 10- 11-mers [default: FALSE].
  --extselfsim=<extselfsim>      Perform extended self-similarity check; only compatible with 9-mers [default: FALSE].
  --selflist=<selflist>          Add predicted self-epitopes to self-similarity check requires length- & HLA-matched selflist [default: FALSE].
  --panversion=<panversion>      netMHCpan version [default: 3].
  --debug                        Run Neolution in debugging mode [default: FALSE].
  --copyinput=<copyinput>        Copy parsed input files [default: FALSE].
  --logfile=<logfile>            When defined write messages to this filename [default: NA].
  --verbose=<verbose>            Be chatty [default: TRUE].
  --help                         Show this help text.
  --usage                        Show help and short example usage." -> doc


if (T) {
  # script_dir <- dirname(sys.frame(1)$ofile)
  script_dir <- '~/libs/neolution'
  suppressWarnings(suppressMessages(devtools::load_all(script_dir)))
} else {
  library(neolution)
}
runParameters <- processDocOpt(docopt(doc))

performPredictions(runParameters = runParameters, unique_cols = NULL)

# vim: set ft=r:
